repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        types: [python]
        files: ^(penpot_mcp|tests)/.*\.py$

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
        types: [python]
        files: ^(penpot_mcp|tests)/.*\.py$

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.13.0
    hooks:
    -   id: pyupgrade
        args: [--py312-plus]
        types: [python]
        files: ^(penpot_mcp|tests)/.*\.py$

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
        args: [--aggressive, --aggressive, --select=E,W]
        types: [python]
        files: ^(penpot_mcp|tests)/.*\.py$
        additional_dependencies: [setuptools>=65.5.0] 